apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: g3-eks
  labels:
    app: fms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fms
  template:
    metadata:
      labels:
        app: fms
    spec:
      containers:
        - name: g3-eks-codepipeline
          image: 124355663661.dkr.ecr.ap-northeast-3.amazonaws.com/g3-eks-codepipeline:frontend
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL_LEAVE
              value: "http://leave-service.g3-eks.svc.cluster.local:8080"
            - name: REACT_APP_API_URL_USER
              value: "http://user-service.g3-eks.svc.cluster.local:8082"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leave-deployment
  namespace: g3-eks
  labels:
    app: lms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lms
  template:
    metadata:
      labels:
        app: lms
    spec:
      containers:
        - name: leave-service
          image: 124355663661.dkr.ecr.ap-northeast-3.amazonaws.com/leave-service:latest
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: g3-eks
  labels:
    app: ums
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ums
  template:
    metadata:
      labels:
        app: ums
    spec:
      containers:
        - name: user-service
          image: 124355663661.dkr.ecr.ap-northeast-3.amazonaws.com/user-service:latest
          ports:
            - containerPort: 8082
