---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: g3-eks
  labels:
    app: fms
spec:
  type: LoadBalancer
  selector:
    app: fms
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: leave-service
  namespace: g3-eks
  labels:
    app: lms
spec:
  type: ClusterIP
  selector:
    app: lms
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: g3-eks
  labels:
    app: ums
spec:
  type: ClusterIP
  selector:
    app: ums
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
